### ISSUE TITLE
Prepare for stateless callbacks

### ISSUE THREAD

**Issue by iphydf** [abbat/pytoxcore#11]
See toktok/toxcore#40. The toktok repo currently has version 0.0.1. The API will not change in that version. You can test for this version specifically to `#if/#endif` the change.

**Comment by abbat** [comment]
What will we do if someone also fork toxcore, change other api and set version to 0.0.1?

**Comment by iphydf** [comment]
Then you won't be compatible with that fork. If that happens, we'll need to talk with that person and find a way forward. Right now, that is not a concern, because we're the only people actively developing toxcore.

**Comment by abbat** [comment]
Why you don't want to add project/fork specific define? It is nothing costs, easy to add and solves the problem of unexpected breakage of build process in the long run.

**Comment by GrayHatter** [comment]
> Why you don't want to add project/fork specific define? It is nothing costs, easy to add and solves the problem of unexpected breakage of build process in the long run.

Ignoring irungentoo's version of toxcore: If someone else forks toxcore, and they break API/ABI compatibily, why is that our problem?

**Comment by abbat** [comment]
This is not your problem, but potentially problem of libtoxcore users who develop libraries and clients and using it. Just remember ffmpeg vs libav - it was (and still in Debian for example) a pain for developers and users. What worries me is that this story repeats itself.

**Comment by GrayHatter** [comment]
I have no idea what the ffmpeg vs libav issue was, but regardless I'd still
rather burn that bridge when we get to it.

**Comment by abbat** [comment]
Anyway, code added through `#if/#endif`
