### ISSUE TITLE
When try to build: fatal error: tox/tox.h

### ISSUE THREAD

**Issue by kden416** [abbat/pytoxcore#12]
In file included from pytoxcore.h:23:0,
                 from pytoxav.h:23,
                 from pytox.c:20:
pytox.h:31:21: fatal error: tox/tox.h: Нет такого файла или каталога
compilation terminated.

**Comment by kden416** [comment]
while pytoxcore instlalled from ubuntu repo in python interpreter:
>>>import pytoxcore
>>>ImportError: libtoxcore.so.0: cannot open shared object file: No such file or directory

**Comment by abbat** [comment]
To compile statically you need (at least) [tox-libtoxcore-dev, tox-libsodium-dev packages](https://github.com/abbat/tox.pkg).

Which repo you use for Ubuntu and which Ubuntu version?

**Comment by kden416** [comment]
something was broken when install, reinstall and rebuild fix it
may be, try to build toxcore from sources was not successfully.
so, i installed tox-libtoxcore, tox-libtoxcore-dev from repo ubuntu 16.04 and
setup.py build  ===> setup.py install
all works fine
