### ISSUE TITLE
Add reference to PyTox

### ISSUE THREAD

**Issue by aitjcize** [abbat/pytoxcore#4]
Hi, 

I believe the code in this repository is partially based on PyTox(https://github.com/aitjcize/PyTox). Since the original code is GPL licensed. Could you please add reference to the original project?

Thanks.

**Comment by abbat** [comment]
Reference is in AUTHORS, or you want to add reference to other file?

**Comment by aitjcize** [comment]
Oh, didn't spot that. That's good enough. Thanks.
